### ISSUE TITLE
 Auto hide app

### ISSUE THREAD

**Issue by Kvanrooyen** [somebeaver/Cardinal-Server#1]
When you open the app from the taskbar and then click outside the app it should auto close, instead of having to click on the icon again

**Comment by Kvanrooyen** [comment]
![ZTDVWFmf0y](https://user-images.githubusercontent.com/17731202/121788751-ab6e6000-cbc7-11eb-90e5-bb3b40453672.gif)

**Comment by somebeaver** [comment]
Added in v0.4.3
